#!/bin/bash

# Script Name:                  loghistory
# Author:                       Breanna Taylor
# Date of latest revision:      10/25/2023
# Purpose:                      all about function practice

# Declaration of variables

log_login_history(){
/var/log/wtmp
grep"Accepted password" "$AUTH_LOG"
}
$login_history



# Declaration of functions

#End